version: '3.7'
# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: spatial
      POSTGRES_PASSWORD: test4now
      POSTGRES_DB: spatial
    ports:
      - "5433:5432"
    volumes:
      # The official postgres docker image will run .sql scripts found in the /docker-entrypoint-initdb.d/ folder.
      - ./db/initdb.d:/docker-entrypoint-initdb.d/
