version: '3.7'

services:
  spatial-api:
    container_name: spatial-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
      - FLASK_APP=spatialapi
      - FLASK_ENV=development
    volumes:
      - ./server:/app/server
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - '5001:5000'
