openapi: 3.0.0
info:
  description: 'The HuBMAP Spatial API is a standard RESTful web service with create operations.'
  version: 1.0.0
  title: HuBMAP Spatial API
  contact:
    name: HuBMAP Help Desk
    email: api-developers@hubmapconsortium.org
  license:
    name: MIT License
    url: 'https://github.com/hubmapconsortium/spatial-api/blob/main/license.txt'
servers:
  - url: 'https://spatial.api.hubmapconsortium.org'

paths:
  '/rebuild-annotation-details':
    put:
      summary: Rebuild the tables containing the annotation details
      operationId: db_rebuild_annotation_details
      responses:
        '200':
          description: Processed
  '/samples/cell-type-counts':
    put:
      summary: The sample cell type counts are returned by ingest-api
      operationId: samples_extracted_cell_type_counts_from_secondary_analysis_files
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtractedCellTypeCountsRequest'
      responses:
        '202':
          description: Accepted for Processing
  '/samples/reindex-all':
    put:
      summary: For all samples, delete the old sample information and replace it by processing the current data
      operationId: samples_all_reindex
      responses:
        '202':
          description: Accepted for Processing
  '/samples/{sample_uuid}/reindex':
    put:
      summary: For the sample_uuid given, delete the old sample information and replace it by processing the current data
      operationId: samples_sample_uuid_reindex
      responses:
        '202':
          description: Accepted for Processing
  '/samples/organ/<organ_code>/reindex':
    put:
      summary: For all samples associated with the organ_code, delete the old sample information and replace it by processing the current data
      operationId: samples_organ_code_reindex
      responses:
        '202':
          description: Accepted for Processing
  '/search/hubmap-id/{hubmap_id}/radius/{radius}/target/{target}':
    get:
      summary: List the hubmap_ids associated with the target body that are located within the radius of the centroid of the hubmap_id specified
      operationId: search_hubmap_id_to_radius
      parameters:
        - name: hubmap_id
          in: path
          required: true
          description: The initial starting point for the search
          schema:
            type: string
            example: HBM634.MMGK.572
        - name: radius
          in: path
          required: true
          description: The radius in mm to search from the initial starting point
          schema:
            type: number
            example: 150.5
        - name: target
          in: path
          required: true
          description: The target human, currently either VHMale, or VFemale
          schema:
            type: string
            example: VHMale
      responses:
        '200':
          description: List of HubMAP IDs that meet the radius and target criteria given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HubMAPIds'
        '400':
          description: Parameter is incorrect or incorrectly formed
        '404':
          description: No HubMAP IDs were found
  '/spatial-search/hubmap-id':
    post:
      summary: List the hubmap_ids (with samples having the cell_type) associated with the target body that are located within the radius of the centroid of the hubmap_id specified
      operationId: spatial_search_hubmap_id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpatialSearchRequest'
      responses:
        '200':
          description: List of HubMAP IDs that meet the radius, target, and cell_type criteria given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HubMAPIds'
        '400':
          description: Parameter is incorrect or incorrectly formed
        '404':
          description: No HubMAP IDs were found
  '/point-search':
    post:
      summary: List the hubmap_ids associated with the target body that are located within the radius of the point <x, y, z>
      operationId: spatial_search_point
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpatialSearchPointRequest'
      responses:
        '200':
          description: List of HubMAP IDs that meet the radius and target criteria given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HubMAPIds'
        '400':
          description: Parameter is incorrect or incorrectly formed
        '404':
          description: No HubMAP IDs were found
  '/status':
    get:
      summary: Get the status of the server
      operationId: get_status
      responses:
        '200':
          description: List of HubMAP IDs that meet the radius and target criteria given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
components:
  schemas:
    HubMAPIds:
      type: object
      properties:
        hubmap_ids:
          type: array
          description: "List of HubMAP IDs."
          items:
            type: string
          example: ["HBM457.NNQN.252", "HBM627.QCRL.874"]
    SpatialSearchRequest:
      type: object
      properties:
        target:
          type: string
          example: VHMale
        radius:
          type: number
          example: 120.4
        hubmap_id:
          type: string
          example: HBM457.NNQN.252
        cell_type:
          type: string
          example: Connecting Tubule
    SpatialSearchPointRequest:
      type: object
      properties:
        target:
          type: string
          example: VHMale
        radius:
          type: number
          example: 120.4
        x:
          type: number
          example: 10
        y:
          type: number
          example: 20
        z:
          type: number
          example: 20
    ExtractedCellTypeCountsRequest:
      type: object
      properties:
        sample_uuid:
          type: string
          example: 1.0.0
        cell_type_counts:
          type: object
    StatusResponse:
      type: object
      properties:
        version:
          type: string
          example: 1.0.0
        build:
          type: string
          example: build
        database_connection:
          type: string
          example: True